---
title: "Core API: clustering from long-format data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Core API: clustering from long-format data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.align = "center")
knitr::opts_chunk$set(fig.height = 6.5, fig.width = 7.5, dpi = 90, out.width = '100%')
knitr::opts_chunk$set(comment = "#>")
```

```{r, warning = FALSE, message = FALSE}
library(sfclust)
library(stars)
library(igraph)
library(sf)
library(ggplot2)
```

```{r}
data(stbinom)
geometry <- st_get_dimension_values(stbinom, "geometry")
```

```{r}
df <- data_all(stbinom)
head(df)
```

```{r}
adj_bin <- as(sf::st_touches(geometry), "matrix") * 1L
weights <- runif(length(adj_bin))
adj <- adj_bin * weights
```

```{r}
geodata <- genclust(adj, nclust = 10)

result <- sfclust(
  df, adj, graphdata = geodata, fun_col = "idf_time",
  formula = cases ~ poly(idf_time, 2) + f(id),
  family  = "binomial", Ntrials = population,
  niter = 5, burnin = 0, thin = 1, nmessage = 5
)
```

```{r}
print(result)
summary(result)
```

```{r}
plot_clusters_fitted(result)
plot_log_mlik(result)
```
